image:
  file: .github/dockerfiles/Dockerfile.gitpod-base

tasks:
  - name: Web app
    init: yarn install && yarn run build
    command: yarn run start
  - name: Setup node
    init: sh ./scripts/setup-node.sh
    command: ../chocolate-node/target/release/chocolate --dev
  - name: Pin server
    init: npm install --prefix=functions
    command: npm run start-dev --prefix=functions
  - name: Auth server
    init: npm install --prefix=polkadot-apac-hackathon/auth-server
    command: npm run start-dev --prefix=polkadot-apac-hackathon/auth-server
  - name: IPFS node
    command: ipfs init --profile server && ipfs daemon

vscode:

  extensions:
    # Linters
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    
    # Tools 
    - rangav.vscode-thunder-client
    # - nrwl.angular-console
    # - firsttris.vscode-jest-runner
    # - styled-components.vscode-styled-components
    
    # Paths and npm
    - visualstudioexptteam.vscodeintellicode
    - christian-kohler.path-intellisense
    - christian-kohler.npm-intellisense
    
    # Language servers
    - redhat.vscode-yaml
    - ahmadalli.vscode-nginx-conf
    - ecmel.vscode-html-css
    # - bradlc.vscode-tailwindcss
    
    # convenience
    - yzhang.markdown-all-in-one
    - github.copilot
    - rubbersheep.gi
    - oouo-diogo-perdigao.docthis
    - mads-hartmann.bash-ide-vscode
    
    # Visuals
    - oderwat.indent-rainbow
