/* eslint-disable no-use-before-define */
// Generated by https://quicktype.io

import { AccountId } from '@polkadot/types/interfaces';
// eslint-disable-next-line import/no-unresolved
import { ProjectID } from 'chocolate/interfaces';

interface NewGenericProjectWithIndex<Num> {
  Id: Num;
  project: GenericNewProject<Num>;
}
export type HumanNewProjectWithIndex = NewGenericProjectWithIndex<string>;
export type JSONNewProjectWithIndex = NewGenericProjectWithIndex<number>;

export type ChainMetaData = string;

interface GenericChainProject<Num> {
  ownerID: string;
  badge?: boolean;
  metadata: ChainMetaData;
  proposalStatus: ProposalStatus;
  reward: Num;
  totalUserScores: Num;
  totalReviewScore: Num;
  numberOfReviews: Num;
}
export type JSONChainProject = GenericChainProject<number>;
export type HumanChainProject = GenericChainProject<string>;
export interface ProposalStatus {
  status: Status['_enum'];
  reason: Reason['_enum'];
}

export interface Reason {
  _enum: Partial<ReasonEnum>;
}

export interface ReasonEnum {
  Other: string;
  InsufficientMetaData: null;
  Malicious: null;
  PassedRequirements: null;
}

interface GenericChainReview<Num> {
  proposalStatus: ProposalStatus;
  userID: string;
  content: string;
  projectID: Num;
  pointSnapshot: Num;
  reviewScore: Num;
}
export type JSONChainReview = GenericChainReview<number>;
export type HumanChainReview = GenericChainReview<string>;

export interface NewMetaData {
  /** If doesn't exist polyfill */
  Link?: string;
  name: string;
  description: string;
  /** @deprecated, use icon instead, only the first struct makes use of this, the rest use icon */
  image?: string;
  icon?: string;
  date: number;
}

interface GenericNewProject<Num> extends Omit<GenericChainProject<Num>, 'metadata'> {
  metadata: NewMetaData;
}
export type HumanNewProject = GenericNewProject<string>;
export type JSONNewProject = GenericNewProject<number>;
// store on ipfs fully
export interface ReviewContent {
  reviewText: string;
  rating: number;
}

interface NewGenericReview<Num> extends Omit<GenericChainReview<Num>, 'content'> {
  content: ReviewContent;
}
export type HumanNewReview = NewGenericReview<string>;
export type JSONNewReview = NewGenericReview<number>;
interface GenericTableSetReview<Num> extends NewGenericReview<Num> {
  project: GenericNewProject<Num>;
}
export type HumanTableSetReview = GenericTableSetReview<string>;
export type JSONTableSetReview = GenericTableSetReview<number>;

export interface Status {
  _enum: 'Proposed' | 'Accepted' | 'Rejected';
}

interface GenericUser<Num> {
  rankPoints: Num;
  projectId?: Num;
}
export type HumanUser = GenericUser<string>;
export type JSONUser = GenericUser<number>;

export type ReviewKeyAl = [AccountId, ProjectID];
